name: Lint and Type Check

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    typecheck:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

              with:
                  node-version: "20"
                  cache: "bun"

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Run TypeScript Type Check
              run: bun run typecheck

    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

              with:
                  node-version: "20"
                  cache: "bun"

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Run Lint
              run: bun run lint

    style:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

              with:
                  node-version: "20"
                  cache: "bun"

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Check Formatting
              run: bun run style