name: Tests

on:
  pull_request:
    types:
      - opened

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Cache Bun modules
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: bun-modules-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            bun-modules-
            
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Run tests with coverage
        run: bun test --coverage
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage-final.json
          fail_ci_if_error: false
  e2e-tests:
    name: Run E2E tests
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Install Playwright browsers
        run: bunx playwright install --with-deps
        
      - name: Run Playwright tests
        run: bunx playwright test
        
      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      
